travis:
  secure:
    BINSTAR_TOKEN: VlB5RY0RWvGXG9Nu3Kf1kepjw1B5BZrihiSC1wbJvQ8kIdXo+CDcfHGbTGMPLhNy2yTQroAZkNcQfWiN21iUKcR/ePt8XcMotRQLpWbj/pH503FZ/gBKsiXbdjcL4WhQctBIwXixVrlKFdbcJC0p2HX9qgMnGVAvZOE0iSEwhBzW7MAp1LcPH/RYwJW7Y2QR/p3O8vp4yqg0a0hgFxBNojGf3JKsF3P02qH1AumH2qsYZMlYzOPaGcc7N85MUQV8qwnG0hAMoYDJ2A0ffCJPCtPuYcz0r423wIJKsmEAdL2pvU9d78sgXx4YLu/p6J6cmO8jM5d0Ntsgs/bnWQMk2uqUFjK6+u/L9LEnGE06owpxX+hvUn5GqOhoCBK5x4hvyus+G9wv/IQegCAuNwp4t1ljpgJxRzCSzso4j6xt132AT7OYRQ6U3ktDy4NmvRhbmEQ1EM9YwAtSDmL44uByL3GLcq/ujj1CZqbHRibSN58IKb2vauxcNUEN4ym414+cbiFI7XJl+19IcUnhHE2s6M8bhBnYm5mnnnLXdCF1xFzAoDY/E/1TgF572a+jF9qtSwJ664SclVBUYfXprZJKtbeD92Zwl00Hpmxfacv6Yh+ecBdLB7HpSFAQYBMyVKLEi0yL9AXxY8ke3qPX87Da7SMs5OMdrXwyKHLyY+mPnxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
